BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Products" (
	"ProdID"	INTEGER NOT NULL,
	"Prod_Name"	TEXT,
	"Prod_Desc"	TEXT,
	"Prod_Price"	REAL,
	"Prod_Quantity"	INTEGER,
	"Prod_Category"	TEXT,
	"Prod_Mainpic"	TEXT,
	"Prod_Pic1"	TEXT,
	"Prod_Pic2"	TEXT,
	"Prod_Pic3"	TEXT,
	"Prod_Pic4"	TEXT,
	PRIMARY KEY("ProdID")
);
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (101,'Super Smash Bros. Ultimate - Nintendo Switch','Gaming icons clash in the ultimate brawl you can play anytime, anywhere! Smash rivals off the stage as new characters Simon Belmont and King K. Rool join Inkling, Ridley, and every fighter in Super Smash Bros. history. Enjoy enhanced speed and combat at new stages based on the Castlevania series, Super Mario Odyssey, and more!
Having trouble choosing a stage? Then select the Stage Morph option to transform one stage into another while battling—a series first! Plus, new echo fighters Dark Samus, Richter Belmont, and Chrom join the battle. Whether you play locally or online, savor the faster combat, new attacks, and new defensive options, like a perfect shield. Jam out to 900 different music compositions and go 1-on-1 with a friend, hold a 4-player free-for-all, kick it up to 8-player battles and more! Feel free to bust out your GameCube controllers—legendary couch competitions await—or play together anytime, anywhere!',1890.0,100,'Nintendo','bsadpic/mainpic/Nintendo/2.jpg','bsadpic/inpic/Nintendo/2/in1.jpg','bsadpic/inpic/Nintendo/2/in2.jpg','bsadpic/inpic/Nintendo/2/in3.jpg','bsadpic/inpic/Nintendo/2/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (102,'The Legend of Zelda: Breath of the Wild','Forget everything you know about The Legend of Zelda games. Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. Travel across vast fields, through forests, and to mountain peaks as you discover what has become of the kingdom of Hyrule in this stunning Open-Air Adventure. Now on Nintendo Switch, your journey is freer and more open than ever. Take your system anywhere, and adventure as Link any way you like.',2061.86,100,'Nintendo','bsadpic/mainpic/Nintendo/2.jpg','bsadpic/inpic/Nintendo/2/in1.jpg','bsadpic/inpic/Nintendo/2/in2.jpg','bsadpic/inpic/Nintendo/2/in3.jpg','bsadpic/inpic/Nintendo/2/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (103,'Animal Crossing: New Horizons - Nintendo Switch','Escape to a deserted island and create your own paradise as you explore, create, and customize in the Animal Crossing: New Horizons game. Your island getaway has a wealth of natural resources that can be used to craft everything from tools to creature comforts. You can hunt down insects at the crack of dawn, decorate your paradise throughout the day, or enjoy sunset on the beach while fishing in the ocean. The time of day and season match real life, so each day on your island is a chance to check in and find new surprises all year round. Get ready to make a splash in your own island paradise. A series of free updates* to the Animal Crossing: New Horizons game for the Nintendo Switch system will deliver new features, including the ability to swim and dive for sea creatures. You''ll also get to interact with fresh faces and discover a variety of new items, including mermaid-themed furniture. These free updates are among some of the new experiences coming to your island life over the course of the summer and beyond.',1890.0,100,'Nintendo','bsadpic/mainpic/Nintendo/2.jpg','bsadpic/inpic/Nintendo/2/in1.jpg','bsadpic/inpic/Nintendo/2/in2.jpg','bsadpic/inpic/Nintendo/2/in3.jpg','bsadpic/inpic/Nintendo/2/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (104,'Super Mario Odyssey - Nintendo Switch','Embark on a cap-tivating, globe-trotting adventure! Join Mario on a massive, globe-trotting 3D adventure and use his incredible new abilities to collect Moons so you can power up your airship, the Odyssey, and rescue Princess Peach from Bowser''s wedding plans!
This sandbox-style 3D Mario adventure—the first since 1996''s beloved Super Mario 64 and 2002''s Nintendo GameCube classic Super Mario Sunshine—is packed with secrets and surprises, and with Mario''s new moves like cap throw, cap jump, and capture, you''ll have fun and exciting gameplay experiences unlike anything you''ve enjoyed in a Mario game before. Get ready to be whisked away to strange and amazing places far from the Mushroom Kingdom!',1890.0,100,'Nintendo','bsadpic/mainpic/Nintendo/2.jpg','bsadpic/inpic/Nintendo/2/in1.jpg','bsadpic/inpic/Nintendo/2/in2.jpg','bsadpic/inpic/Nintendo/2/in3.jpg','bsadpic/inpic/Nintendo/2/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (201,'Star Wars Jedi: Survivor - PC Origin','The story of Cal Kestis continues in Star Wars Jedi: Survivor™, a third person galaxy-spanning action-adventure game from Respawn Entertainment, developed in collaboration with Lucasfilm Games. This narratively-driven, single player title picks up five years after the events of Star Wars Jedi: Fallen Order™ and follows Cal’s increasingly desperate fight as the galaxy descends further into darkness. Pushed to the edges of the galaxy by the Empire, Cal will find himself surrounded by threats new and familiar. As one of the last surviving Jedi Knights, Cal is driven to make a stand during the galaxy’s darkest times – but how far is he willing to go to protect himself, his crew, and the legacy of the Jedi Order?',2061.86,100,'PC','bsadpic/mainpic/PC/1.jpg','bsadpic/inpic/PC/1/in1.jpg','bsadpic/inpic/PC/1/in2.jpg','bsadpic/inpic/PC/1/in3.jpg','bsadpic/inpic/PC/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (202,'The Last of Us Part 1 - PC Steam','Experience the emotional storytelling and unforgettable characters in The Last of Us™, winner of over 200 Game of the Year awards. In a ravaged civilization, where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone. However, what starts as a small job soon transforms into a brutal cross-country journey. Includes the complete The Last of Us single-player story and celebrated prequel chapter, Left Behind, which explores the events that changed the lives of Ellie and her best friend Riley forever.',1980.0,100,'PC','bsadpic/mainpic/PC/1.jpg','bsadpic/inpic/PC/1/in1.jpg','bsadpic/inpic/PC/1/in2.jpg','bsadpic/inpic/PC/1/in3.jpg','bsadpic/inpic/PC/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (203,'Elden Ring Deluxe Edition - PC','GameStop invites you to a mythical world filled with adventure in ELDEN RING Deluxe Edition on PC. Danger lurks in every corner in this action RPG video game. Explore an open world rich with magic, ruins, and combat. Encounter the game’s secrets as you discover the mysteries of ELDEN RING.',2749.26,100,'PC','bsadpic/mainpic/PC/1.jpg','bsadpic/inpic/PC/1/in1.jpg','bsadpic/inpic/PC/1/in2.jpg','bsadpic/inpic/PC/1/in3.jpg','bsadpic/inpic/PC/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (204,'Battlefield 2042 - PC','Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise. In a near-future world transformed by disorder, adapt and overcome dynamically-changing battlegrounds with the help of your squad and a cutting-edge arsenal. With support for 128 players, Battlefield™ 2042 brings unprecedented scale on vast environments across the globe. Players will take on several massive experiences, from updated multiplayer modes like Conquest and Breakthrough to the all-new Hazard Zone and Battlefield Portal.',1374.46,100,'PC','bsadpic/mainpic/PC/1.jpg','bsadpic/inpic/PC/1/in1.jpg','bsadpic/inpic/PC/1/in2.jpg','bsadpic/inpic/PC/1/in3.jpg','bsadpic/inpic/PC/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (301,'Resident Evil 4 - PlayStation 5','Resident Evil™ 4 joins Leon S. Kennedy six years after his hellish experiences in the biological disaster of Raccoon City. His unmatched resolve caused him to be recruited as an agent reporting directly to the president of the United States. With the experience of multiple missions on his back, Leon is dispatched to rescue the president’s recently kidnapped daughter. Leon tracks her to a secluded European village, however, after making first contact he discovers a fervor beyond reason grips the local populace. Now, this reimagined tale of survival in the face of overwhelming terror returns to deliver a visually stunning modern gaming experience that is true to the promise of the original release.',1890.0,100,'PlayStation','bsadpic/mainpic/Playstation/1.jpg','bsadpic/inpic/Playstation/1/in1.jpg','bsadpic/inpic/Playstation/1/in2.jpg','bsadpic/inpic/Playstation/1/in3.jpg','bsadpic/inpic/Playstation/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (302,'Hogwarts Legacy - PlayStation 5','Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. For the first time, experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart. Now you can take control of the action and be at the center of your own adventure in the wizarding world. Your legacy is what you make of it. Live the unwritten.',2233.71,100,'PlayStation','bsadpic/mainpic/Playstation/1.jpg','bsadpic/inpic/Playstation/1/in1.jpg','bsadpic/inpic/Playstation/1/in2.jpg','bsadpic/inpic/Playstation/1/in3.jpg','bsadpic/inpic/Playstation/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (303,'God of War Ragnarok Standard Edition - PlayStation 5','Embark on a mythic journey for answers and allies before Ragnarök arrives in God of War Ragnarok on PS5. Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go.
Against a backdrop of Norse Realms torn asunder by the fury of the Aesir, they’ve been trying their utmost to undo the end times. But despite their best efforts, Fimbulwinter presses onward.

Witness the changing dynamic of the father-son relationship as they fight for survival; Atreus thirsts for knowledge to help him understand the prophecy of “Loki”, as Kratos struggles to break free of his past and be the father his son needs.

See for yourself how fate will force a choice upon them: between their own safety or the safety of the realms. All the while, hostile Asgardian forces assemble…',2061.86,100,'PlayStation','bsadpic/mainpic/Playstation/1.jpg','bsadpic/inpic/Playstation/1/in1.jpg','bsadpic/inpic/Playstation/1/in2.jpg','bsadpic/inpic/Playstation/1/in3.jpg','bsadpic/inpic/Playstation/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (304,'WWE 2K23 - PlayStation 5','WWE 2K23 is the latest installment in the long-running series of professional wrestling games developed by 2K Games. the newest game in the series is set to feature an extensive roster of wrestlers and a wide variety of match types and game modes. The WWE 2K23 Roster will include a huge list of superstars from Raw, SmackDown, NXT, and NXT UK, and even WWE Legends!',1718.16,100,'PlayStation','bsadpic/mainpic/Playstation/1.jpg','bsadpic/inpic/Playstation/1/in1.jpg','bsadpic/inpic/Playstation/1/in2.jpg','bsadpic/inpic/Playstation/1/in3.jpg','bsadpic/inpic/Playstation/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (401,'FIFA 23 - Xbox One','EA SPORTS™ FIFA 23 brings The World’s Game to the pitch, with both men’s and women’s FIFA World Cup™ tournaments, the addition of women’s club teams, cross-play features, and new ways to play your favorite modes.',962.02,100,'Xbox','bsadpic/mainpic/Xbox/1.jpg','bsadpic/inpic/Xbox/1/in1.jpg','bsadpic/inpic/Xbox/1/in2.jpg','bsadpic/inpic/Xbox/1/in3.jpg','bsadpic/inpic/Xbox/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (402,'Hogwarts Legacy - Xbox One','Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. For the first time, experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart. Now you can take control of the action and be at the center of your own adventure in the wizarding world. Your legacy is what you make of it. Live the unwritten.',2061.86,100,'Xbox','bsadpic/mainpic/Xbox/1.jpg','bsadpic/inpic/Xbox/1/in1.jpg','bsadpic/inpic/Xbox/1/in2.jpg','bsadpic/inpic/Xbox/1/in3.jpg','bsadpic/inpic/Xbox/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (403,'Red Dead Redemption 2 - Xbox One','The end of the Wild West era has begun. After a robbery gone wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him.',1374.46,100,'Xbox','bsadpic/mainpic/Xbox/1.jpg','bsadpic/inpic/Xbox/1/in1.jpg','bsadpic/inpic/Xbox/1/in2.jpg','bsadpic/inpic/Xbox/1/in3.jpg','bsadpic/inpic/Xbox/1/in4.jpg');
INSERT INTO "Products" ("ProdID","Prod_Name","Prod_Desc","Prod_Price","Prod_Quantity","Prod_Category","Prod_Mainpic","Prod_Pic1","Prod_Pic2","Prod_Pic3","Prod_Pic4") VALUES (404,'The Amazing Spider-Man 2 - Xbox One','Following the events of the second film, the Amazing Spider-Man 2 video gameon Xbox One follows Spider-Man in his quest to hunt down criminals and stop the uprising of violence and crime in Manhattan. Featuring a wide cast of villains as well as fan-favorite characters from the franchise, you’ll take down foes in and expansive NYC using an all-new arsenal of web-shooting capabilities and acrobatic combat.',2061.86,100,'Xbox','bsadpic/mainpic/Xbox/1.jpg','bsadpic/inpic/Xbox/1/in1.jpg','bsadpic/inpic/Xbox/1/in2.jpg','bsadpic/inpic/Xbox/1/in3.jpg','bsadpic/inpic/Xbox/1/in4.jpg');
COMMIT;
